In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split

#### Escalamiento de los datos

In [3]:
#Cargamos la base de datos
x = pd.read_csv('dataEntreno.csv')
x.head()

,production_budget,worldwide_gross,title_year,aspect_ratio,duration,cast_total_facebook_likes,budget,imdb_score,gross
0,425000000.0,2.783919e+09,2009.000000,1.780000,178.000000,4834.0,2.370000e+08,7.9,7.605058e+08
1,306000000.0,2.058662e+09,2002.102628,2.126683,108.552703,143.0,3.712339e+07,7.1,4.819001e+07
2,300000000.0,9.634204e+08,2007.000000,2.350000,169.000000,48350.0,3.000000e+08,7.1,3.094042e+08
3,300000000.0,8.796209e+08,2015.000000,2.350000,148.000000,11700.0,2.450000e+08,6.8,2.000742e+08
4,275000000.0,1.084439e+09,2012.000000,2.350000,164.000000,106759.0,2.500000e+08,8.5,4.481306e+08

In [4]:
#Extraemos nuestra variable target
y = x['worldwide_gross']
#Eliminamos la variable de nuestra base
x.drop('worldwide_gross',axis=1,inplace=True)
x.tail()

,production_budget,title_year,aspect_ratio,duration,cast_total_facebook_likes,budget,imdb_score,gross
4056,7000.0,2004.0,1.850000,77.0,368.0,7.000000e+03,7.0,4.247600e+05
4057,7000.0,2005.0,2.126683,80.0,0.0,7.000000e+03,6.3,7.007100e+04
4058,7000.0,2005.0,2.126683,84.0,93.0,3.250000e+03,7.8,4.819001e+07
4059,3967.0,2012.0,2.350000,100.0,2386.0,3.712339e+07,6.3,1.044300e+04
4060,1100.0,2004.0,1.850000,90.0,163.0,1.100000e+03,6.6,8.522200e+04

In [5]:
#Creamos nuestos tabulares y features(target) de entreno y de prueba
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [6]:
#El 75% es para entreno y el 25% para prueba
len(x_train)/len(x)

0.7498153164245259

Existen distintas estrategias de escalamiento de tus features, pero la más común es la estandarización donde convertimos la variable para que la distribución de esta siga una distribución que es Gaussiana de media 0 y de desviación estandar 1.

In [7]:
from sklearn.preprocessing import StandardScaler
#Instancio el estimador
scaler = StandardScaler()
#Entreno el estimador
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
#Hiperparametro
scaler.mean_

array([3.34547374e+07, 2.00209762e+03, 2.13191743e+00, 1.08914606e+02,
       1.01700056e+04, 3.68931467e+07, 6.47665025e+00, 4.87418045e+07])

In [9]:
scaler.scale_

array([4.15348276e+07, 1.21539416e+01, 7.66392784e-01, 2.35801926e+01,
       1.58619667e+04, 6.13814409e+07, 1.06834891e+00, 6.51414719e+07])

In [10]:
x.values

array([[4.25000000e+08, 2.00900000e+03, 1.78000000e+00, ...,
        2.37000000e+08, 7.90000000e+00, 7.60505847e+08],
       [3.06000000e+08, 2.00210263e+03, 2.12668290e+00, ...,
        3.71233913e+07, 7.10000000e+00, 4.81900113e+07],
       [3.00000000e+08, 2.00700000e+03, 2.35000000e+00, ...,
        3.00000000e+08, 7.10000000e+00, 3.09404152e+08],
       ...,
       [7.00000000e+03, 2.00500000e+03, 2.12668290e+00, ...,
        3.25000000e+03, 7.80000000e+00, 4.81900113e+07],
       [3.96700000e+03, 2.01200000e+03, 2.35000000e+00, ...,
        3.71233913e+07, 6.30000000e+00, 1.04430000e+04],
       [1.10000000e+03, 2.00400000e+03, 1.85000000e+00, ...,
        1.10000000e+03, 6.60000000e+00, 8.52220000e+04]])

In [11]:
scaler.transform(x_train)

array([[-0.14336733, -1.57131096,  0.28455718, ..., -0.1530291 ,
         0.1154583 ,  0.29410136],
       [-0.61285285, -0.2548656 , -0.3678498 , ..., -0.4707147 ,
        -0.72696311, -0.47432802],
       [-0.70915757, -2.06497797, -0.9941605 , ..., -0.53588098,
         1.51949399, -0.14647818],
       ...,
       [-0.34801487,  0.73246842, -0.3678498 , ..., -0.27521587,
        -0.72696311,  0.79137069],
       [ 0.87987033,  0.81474625,  0.28455718, ...,  0.62082044,
        -0.53975835, -0.15708062],
       [ 0.27796582, -0.41942127,  0.28455718, ...,  0.13207336,
        -1.47578214, -0.71517058]])

In [12]:
x_train_scale, x_test_scaled = (scaler.transform(x_train), scaler.transform(x_test))

In [13]:
from sklearn.linear_model import Lasso

In [14]:
model = Lasso()
model_scaled = Lasso()
model.fit(x_train,y_train)
model_scaled.fit(x_train_scale,y_train)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4.523431575059091e+18, tolerance: 9546471001925496.0
  positive)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [15]:
#Los modelos de regresión no se ven afectados por el escalamiento de las features. Los de clasificación sí.
print(model.score(x_test,y_test))
print(model_scaled.score(x_test_scaled,y_test))

0.8500724882603596
0.8500724903025733

#### Simplificar las transformaciones con pipelines


Para hacer el código más reproducible, y para evitar tener que aplicar multiples veces una misma transformación es recomendable utilizar  sklearn.pipeline.make_pipeline que permite encadenar transformaciones en los modelos.

In [16]:
from sklearn.pipeline import make_pipeline

In [17]:
model_scaled = make_pipeline(StandardScaler(), Lasso())
model_scaled.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('lasso',
                 Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                       max_iter=1000, normalize=False, positive=False,
                       precompute=False, random_state=None, selection='cyclic',
                       tol=0.0001, warm_start=False))],
         verbose=False)

In [18]:
print(model_scaled.score(x_test,y_test))

0.8500724903025733

#### Crear nuevas features de forma automática

In [19]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
from sklearn.preprocessing import PolynomialFeatures

In [21]:
transformer = PolynomialFeatures(2)
transformer

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False,
                   order='C')

In [22]:
transformer.fit_transform(a)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [23]:
x.shape

(4061, 8)

Fit and transform se hacen al mismo tiempo con fit_transform, fit_trasform puede generar mas fiatures, puede ser riesgoso

In [24]:
transformer = PolynomialFeatures(2)
transformer.fit_transform(x).shape

(4061, 45)

In [25]:
model_poly = make_pipeline(PolynomialFeatures(2),Lasso())
model_poly.fit(x_train,y_train)
model_poly.score(x_test,y_test)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4.682498160101331e+18, tolerance: 9546471001925496.0
  positive)

0.8096398406060525

In [26]:
model = Lasso()
model.fit(x_train,y_train)
model.score(x_test,y_test)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4.523431575059091e+18, tolerance: 9546471001925496.0
  positive)

0.8500724882603596

# Creando feature catgoricas

Encoding one-hot

In [27]:
data = pd.DataFrame([['Chile','Colombia','Colombia'],['Hombre','Mujer','Hombre','Mujer']])
data = data.T
data.columns = pd.Index(['pais','genero'])
data

       pais  genero
0     Chile  Hombre
1  Colombia   Mujer
2  Colombia  Hombre
3      None   Mujer

In [28]:
pd.get_dummies(data)

   pais_Chile  pais_Colombia  genero_Hombre  genero_Mujer
0           1              0              1             0
1           0              1              0             1
2           0              1              1             0
3           0              0              0             1

In [29]:
movies_obj = pd.read_csv('./movies_obj.csv')
movies_obj

,movie_title,color,language,country,genres,content_rating,plot_keywords,director_name,actor_1_name,actor_2_name,actor_3_name
0,Avatar,Color,English,USA,Action|Adventure|Fantasy|Sci-Fi,PG-13,avatar|future|marine|native|paraplegic,James Cameron,CCH Pounder,Joel David Moore,Wes Studi
1,Pirates of the Caribbean: At World's End,Color,English,USA,Action|Adventure|Fantasy,PG-13,goddess|marriage ceremony|marriage proposal|pi...,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport
2,Spectre,Color,English,UK,Action|Adventure|Thriller,PG-13,bomb|espionage|sequel|spy|terrorist,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman
3,The Dark Knight Rises,Color,English,USA,Action|Thriller,PG-13,deception|imprisonment|lawlessness|police offi...,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt
4,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,NaN,Documentary,NaN,NaN,Doug Walker,Doug Walker,Rob Walker,NaN
5,John Carter,Color,English,USA,Action|Adventure|Sci-Fi,PG-13,alien|american civil war|male nipple|mars|prin...,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker
6,Spider-Man 3,Color,English,USA,Action|Adventure|Romance,PG-13,sandman|spider man|symbiote|venom|villain,Sam Raimi,J.K. Simmons,James Franco,Kirsten Dunst
7,Tangled,Color,English,USA,Adventure|Animation|Comedy|Family|Fantasy|Musi...,PG,17th century|based on fairy tale|disney|flower...,Nathan Greno,Brad Garrett,Donna Murphy,M.C. Gainey
8,Avengers: Age of Ultron,Color,English,USA,Action|Adventure|Sci-Fi,PG-13,artificial intelligence|based on comic book|ca...,Joss Whedon,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson
9,Harry Potter and the Half-Blood Prince,Color,English,UK,Adventure|Family|Fantasy|Mystery,PG,blood|book|love|potion|professor,David Yates,Alan Rickman,Daniel Radcliffe,Rupert Grint
10,Batman v Superman: Dawn of Justice,Color,English,USA,Action|Adventure|Sci-Fi,PG-13,based on comic book|batman|sequel to a reboot|...,Zack Snyder,Henry Cavill,Lauren Cohan,Alan D. Purwin
11,Superman Returns,Color,English,USA,Action|Adventure|Sci-Fi,PG-13,crystal|epic|lex luthor|lois lane|return to earth,Bryan Singer,Kevin Spacey,Marlon Brando,Frank Langella
12,Quantum of Solace,Color,English,UK,Action|Adventure,PG-13,action hero|attempted rape|bond girl|official ...,Marc Forster,Giancarlo Giannini,Mathieu Amalric,Rory Kinnear
13,Pirates of the Caribbean: Dead Man's Chest,Color,English,USA,Action|Adventure|Fantasy,PG-13,box office hit|giant squid|heart|liar's dice|m...,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport
14,The Lone Ranger,Color,English,USA,Action|Adventure|Western,PG-13,horse|outlaw|texas|texas ranger|train,Gore Verbinski,Johnny Depp,Ruth Wilson,Tom Wilkinson
15,Man of Steel,Color,English,USA,Action|Adventure|Fantasy|Sci-Fi,PG-13,based on comic book|british actor playing amer...,Zack Snyder,Henry Cavill,Christopher Meloni,Harry Lennix
16,The Chronicles of Narnia: Prince Caspian,Color,English,USA,Action|Adventure|Family|Fantasy,PG,brother brother relationship|brother sister re...,Andrew Adamson,Peter Dinklage,Pierfrancesco Favino,Damián Alcázar
17,The Avengers,Color,English,USA,Action|Adventure|Sci-Fi,PG-13,alien invasion|assassin|battle|iron man|soldier,Joss Whedon,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson
18,Pirates of the Caribbean: On Stranger Tides,Color,English,USA,Action|Adventure|Fantasy,PG-13,blackbeard|captain|pirate|revenge|soldier,Rob Marshall,Johnny Depp,Sam Claflin,Stephen Graham
19,Men in Black 3,Color,English,USA,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,PG-13,alien|criminal|m.i.b.|maximum security prison|...,Barry Sonnenfeld,Will Smith,Michael Stuhlbarg,Nicole Scherzinger
20,The Hobbit: The Battle of the Five Armies,Color,English,New Zealand,Adventure|Fantasy,PG-13,army|elf|hobbit|middle earth|orc,Peter Jackson,Aidan Turner,Adam Brown,James Nesbitt
21,The Amazing Spider-Man,Color,English,USA,Action|Adventure|Fantasy,PG-13,lizard|outcast|spider|spider man|teenager,Marc Webb,Emma Stone,Andrew Garfield,Chris Zylka
22,Robin Hood,Color,English,USA,Action|Adventure|Drama|History,PG-13,1190s|archer|england|king of england|robin hood,Ridley Scott,Mark Addy,William Hurt,Scott Grimes
23,The Hobbit: The Desolation of Smaug,Color,English,USA,Adventure|Fantasy,PG-13,dwarf|elf|lake town|mountain|sword and sorcery,Peter Jackson,Aidan Turner,Adam Brown,James Nesbitt
24,The Golden Compass,Color,English,USA,Adventure|Family|Fantasy,PG-13,children|epic|friend|girl|quest,Chris Weitz,Christopher Lee,Eva Green,Kristin Scott Thomas
25,King Kong,Color,English,New Zealand,Action|Adventure|Drama|Romance,PG-13,animal name in title|ape abducts a woman|goril...,Peter Jackson,Naomi Watts,Thomas Kretschmann,Evan Parke
26,Titanic,Color,English,USA,Drama|Romance,PG-13,artist|love|ship|titanic|wet,James Cameron,Leonardo DiCaprio,Kate Winslet,Gloria Stuart
27,Captain America: Civil War,Color,English,USA,Action|Adventure|Sci-Fi,PG-13,based on comic book|knife|marvel cinematic uni...,Anthony Russo,Robert Downey Jr.,Scarlett Johansson,Chris Evans
28,Battleship,Color,English,USA,Action|Adventure|Sci-Fi|Thriller,PG-13,box office flop|hawaii|naval|oahu hawaii|ship,Peter Berg,Liam Neeson,Alexander Skarsgård,Tadanobu Asano
29,Jurassic World,Color,English,USA,Action|Adventure|Sci-Fi|Thriller,PG-13,dinosaur|disaster film|experiment gone wrong|j...,Colin Trevorrow,Bryce Dallas Howard,Judy Greer,Omar Sy
...,...,...,...,...,...,...,...,...,...,...,...
5013,Manito,Color,English,USA,Drama|Family,NaN,ex convict|graduation|manhattan new york city|...,Eric Eason,Franky G,Panchito Gómez,Casper Martinez
5014,Rampage,Color,English,Canada,Action|Crime|Thriller,R,death|first part|killing spree|massacre|murder,Uwe Boll,Matt Frewer,Katharine Isabelle,Michael Paré
5015,Slacker,Black and White,English,USA,Comedy|Drama,R,austin texas|moon|pap smear|texas|twenty somet...,Richard Linklater,Tommy Pallotta,Richard Linklater,Jean Caffeine
5016,Dutch Kills,Color,English,USA,Crime|Drama|Thriller,NaN,NaN,Joseph Mazzella,Tjasa Ferme,Mikaal Bates,Damon Owlia
5017,Dry Spell,Color,English,USA,Comedy|Romance,NaN,anti romantic comedy|dating|divorce|sex comedy...,Travis Legge,Kristen Seavey,Suzi Lorraine,Travis Legge
5018,Flywheel,Color,English,USA,Drama,NaN,baby|car salesman|christian film|pregnancy|use...,Alex Kendrick,Shannen Fields,Lisa Arnold,Janet Lee Dapper
5019,Exeter,Color,English,USA,Horror|Mystery|Thriller,R,asylum|demon|party|secret|teenager,Marcus Nispel,Ashley Tramonte,Brittany Curran,Lindsay MacDonald
5020,The Ridges,NaN,English,USA,Drama|Horror|Thriller,NaN,avatar|college|death|tron|university,Brandon Landers,Robbie Barnes,Alana Kaniewski,Brandon Landers
5021,The Puffy Chair,Color,English,USA,Comedy|Drama|Romance,R,birthday|gift|motel|new york city|upholsterer,Jay Duplass,Mark Duplass,Katie Aselton,Bari Hyman
5022,Stories of Our Lives,Black and White,Swahili,Kenya,Drama,NaN,NaN,Jim Chuchu,Paul Ogola,Olwenya Maina,Mugambi Nthiga
5023,Breaking Upwards,Color,English,USA,Romance,NaN,NaN,Daryl Wein,Zoe Lister-Jones,Heather Burns,Ebon Moss-Bachrach
5024,All Superheroes Must Die,Color,English,USA,Sci-Fi|Thriller,Unrated,arch villain|game of death|kidnapping|superhero,Jason Trost,Sean Whalen,Jason Trost,Nick Principe
5025,Pink Flamingos,Color,English,USA,Comedy|Crime|Horror,NC-17,absurd humor|egg|gross out humor|lesbian|sex,John Waters,Divine,Mink Stole,Edith Massey
5026,Clean,Color,French,France,Drama|Music|Romance,R,jail|junkie|money|motel|singer,Olivier Assayas,Maggie Cheung,Béatrice Dalle,Don McKellar
5027,The Circle,Color,Persian,Iran,Drama,Not Rated,abortion|bus|hospital|prison|prostitution,Jafar Panahi,Fereshteh Sadre Orafaiy,Nargess Mamizadeh,Mojgan Faramarzi
5028,Tin Can Man,Black and White,English,Ireland,Horror,NaN,NaN,Ivan Kavanagh,Patrick O'Donnell,Michael Parle,Emma Eliza Regan
5029,The Cure,Color,Japanese,Japan,Crime|Horror|Mystery|Thriller,NaN,breasts|interrogation|investigation|murder|wat...,Kiyoshi Kurosawa,Kôji Yakusho,Anna Nakagawa,Denden
5030,On the Downlow,Color,English,USA,Drama,NaN,gang initiation|gunplay|hazing|latino|shakespe...,Tadeo Garcia,Tatiana Suarez-Pico,Michael Cortez,Eric Ambriz
5031,Sanctuary; Quite a Conundrum,Color,English,USA,Comedy|Horror|Thriller,NaN,nudity|party|pirate|swimsuit|three word title,Thomas L. Phillips,Julianna Pitt,Joe Coffey,John Lucas
5032,Bang,Color,English,USA,Crime|Drama,NaN,corruption|homeless|homeless man|motorcycle|ur...,Ash Baron-Cohen,Peter Greene,Stanley B. Herman,James Noble
5033,Primer,Color,English,USA,Drama|Sci-Fi|Thriller,PG-13,changing the future|independent film|invention...,Shane Carruth,Shane Carruth,David Sullivan,Casey Gooden
5034,Cavite,Color,English,Philippines,Thriller,Not Rated,jihad|mindanao|philippines|security guard|squa...,Neill Dela Llana,Ian Gamazon,Edgar Tancangco,Quynn Ton
5035,El Mariachi,Color,Spanish,USA,Action|Crime|Drama|Romance|Thriller,R,assassin|death|guitar|gun|mariachi,Robert Rodriguez,Carlos Gallardo,Peter Marquardt,Consuelo Gómez
5036,The Mongol King,Color,English,USA,Crime|Drama,PG-13,jewell|mongol|nostradamus|stepnicka|vallone,Anthony Vallone,Richard Jewell,John Considine,Sara Stepnicka
5037,Newlyweds,Color,English,USA,Comedy|Drama,Not Rated,written and directed by cast member,Edward Burns,Kerry Bishé,Caitlin FitzGerald,Daniella Pineda
5038,Signed Sealed Delivered,Color,English,Canada,Comedy|Drama,NaN,fraud|postal worker|prison|theft|trial,Scott Smith,Eric Mabius,Daphne Zuniga,Crystal Lowe
5039,The Following,Color,English,USA,Crime|Drama|Mystery|Thriller,TV-14,cult|fbi|hideout|prison escape|serial killer,NaN,Natalie Zea,Valorie Curry,Sam Underwood
5040,A Plague So Pleasant,Color,English,USA,Drama|Horror|Thriller,NaN,NaN,Benjamin Roberds,Eva Boehnke,Maxwell Moody,David Chandler
5041,Shanghai Calling,Color,English,USA,Comedy|Drama|Romance,PG-13,NaN,Daniel Hsia,Alan Ruck,Daniel Henney,Eliza Coupe
5042,My Date with Drew,Color,English,USA,Documentary,PG,actress name in title|crush|date|four word tit...,Jon Gunn,John August,Brian Herzlinger,Jon Gunn

#### Es util si el top 20 se encuentra en gran parte de los datos.

In [30]:
movies_obj.apply(pd.Series.nunique).sort_values()

color                2
content_rating      18
language            47
country             65
genres             914
actor_1_name      2097
director_name     2398
actor_2_name      3032
actor_3_name      3521
plot_keywords     4760
movie_title       4917
dtype: int64

# Encoding Binario

In [31]:
#!pip install category_encoders

In [32]:
categorias = pd.read_csv('./categoricals.csv').set_index('Unnamed: 0')
categorias.head()

               actor_1_name      director_name
Unnamed: 0
0               CCH Pounder      James Cameron
1               Doug Walker        Doug Walker
2               Johnny Depp     Gore Verbinski
3           Christoph Waltz         Sam Mendes
4                 Tom Hardy  Christopher Nolan

In [33]:
categorias = categorias.reset_index(drop=True).fillna(0)
categorias

              actor_1_name       director_name
0              CCH Pounder       James Cameron
1              Doug Walker         Doug Walker
2              Johnny Depp      Gore Verbinski
3          Christoph Waltz          Sam Mendes
4                Tom Hardy   Christopher Nolan
5              Johnny Depp      Gore Verbinski
6             Daryl Sabara      Andrew Stanton
7             Brad Garrett        Nathan Greno
8             J.K. Simmons           Sam Raimi
9             J.K. Simmons           Sam Raimi
10         Chris Hemsworth         Joss Whedon
11       Robert Downey Jr.       Anthony Russo
12            Henry Cavill         Zack Snyder
13            Aidan Turner       Peter Jackson
14            Alan Rickman         David Yates
15            Aidan Turner       Peter Jackson
16            Aidan Turner       Peter Jackson
17             Johnny Depp        Rob Marshall
18            Kevin Spacey        Bryan Singer
19      Giancarlo Giannini        Marc Forster
20             Johnny Depp      Gore Verbinski
21            Henry Cavill         Zack Snyder
22          Peter Dinklage      Andrew Adamson
23              Emma Stone           Marc Webb
24     Bryce Dallas Howard     Colin Trevorrow
25         Glenn Morshower         Michael Bay
26             Bingbing Li         Michael Bay
27            Hugh Jackman        Brett Ratner
28               Mark Addy        Ridley Scott
29             Liam Neeson          Peter Berg
...                    ...                 ...
4074  Marcello Mastroianni       Bruno Barreto
4075           Lena Dunham         Lena Dunham
4076             Lin Shaye      William Eubank
4077                     0           Jem Cohen
4078        Paul Schneider  David Gordon Green
4079        Derick Martini        Kevin Jordan
4080             Zoe Kazan   Bradley Rust Gray
4081        Elissa Dowling        Travis Legge
4082           Ringo Starr     Martin Scorsese
4083     Joseph Campanella          Mike Bruce
4084       Andrew Bujalski     Andrew Bujalski
4085       Andrew Bujalski     Andrew Bujalski
4086        Michael Smiley        Ben Wheatley
4087           Jason Mewes         Kevin Smith
4088            Don Brooks       James Bidgood
4089         Stacy Edwards         Neil LaBute
4090        Tommy Pallotta   Richard Linklater
4091          Mark Duplass         Jay Duplass
4092      Zoe Lister-Jones          Daryl Wein
4093                Divine         John Waters
4094         Maggie Cheung     Olivier Assayas
4095   Tatiana Suarez-Pico        Tadeo Garcia
4096          Peter Greene     Ash Baron-Cohen
4097           Kerry Bishé        Edward Burns
4098       Carlos Gallardo    Robert Rodriguez
4099         Shane Carruth       Shane Carruth
4100           Ian Gamazon    Neill Dela Llana
4101        Richard Jewell     Anthony Vallone
4102             Alan Ruck         Daniel Hsia
4103           John August            Jon Gunn

[4104 rows x 2 columns]

In [34]:
X_binenc = pd.concat([x, categorias], axis=1)

In [35]:
X_binenc.shape

(4104, 10)

In [36]:
import category_encoders as ce
encoder = ce.BinaryEncoder(cols=['actor_1_name','director_name'])
encoder

BinaryEncoder(cols=['actor_1_name', 'director_name'], drop_invariant=False,
              handle_missing='value', handle_unknown='value', mapping=None,
              return_df=True, verbose=0)

In [37]:
encoder.fit_transform(X_binenc).shape

(4104, 32)

In [38]:
X_binenc = encoder.fit_transform(X_binenc)
X_binenc.head()

,production_budget,title_year,aspect_ratio,duration,cast_total_facebook_likes,budget,imdb_score,gross,actor_1_name_0,actor_1_name_1,...,director_name_2,director_name_3,director_name_4,director_name_5,director_name_6,director_name_7,director_name_8,director_name_9,director_name_10,director_name_11
0,425000000.0,2009.000000,1.780000,178.000000,4834.0,2.370000e+08,7.9,7.605058e+08,0,0,...,0,0,0,0,0,0,0,0,0,1
1,306000000.0,2002.102628,2.126683,108.552703,143.0,3.712339e+07,7.1,4.819001e+07,0,0,...,0,0,0,0,0,0,0,0,1,0
2,300000000.0,2007.000000,2.350000,169.000000,48350.0,3.000000e+08,7.1,3.094042e+08,0,0,...,0,0,0,0,0,0,0,0,1,1
3,300000000.0,2015.000000,2.350000,148.000000,11700.0,2.450000e+08,6.8,2.000742e+08,0,0,...,0,0,0,0,0,0,0,1,0,0
4,275000000.0,2012.000000,2.350000,164.000000,106759.0,2.500000e+08,8.5,4.481306e+08,0,0,...,0,0,0,0,0,0,0,1,0,1

In [39]:
y.shape

(4061,)

In [40]:
X_binenc.shape

(4104, 32)

In [41]:
X_binenc = X_binenc[X_binenc['production_budget'].notnull()]
X_binenc.shape

(4061, 32)

In [42]:
Xb_train, Xb_test, y_train, y_test = train_test_split(X_binenc,y)

In [43]:
X_train, X_test = (Xb_train[x.columns], Xb_test[x.columns])

In [44]:
model_binenc = Lasso()
model = Lasso()

In [45]:
model_binenc.fit(Xb_train, y_train)
model.fit(X_train, y_train)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.3036486191982607e+18, tolerance: 9384279301811862.0
  positive)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [46]:
print(model_binenc.score(Xb_test, y_test))
print(model.score(X_test, y_test))

0.782778571196947
0.7803605049879538

# Conocimiento experto